os: osx
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/Library/Caches/electron
    - $HOME/Library/Caches/electron-builder
node_js:
  - '9'
before_install:
  - openssl aes-256-cbc -K $encrypted_7029cb32d757_key -iv $encrypted_7029cb32d757_iv -in ./.travis_files/yukimura1227_apple.p12.enc -out ./.travis_files/yukimura1227_apple.p12 -d
before_script:
  - security create-keychain -p travis travis.keychain
  - security default-keychain -s travis.keychain
  - security unlock-keychain -p travis travis.keychain
  - security set-keychain-settings -t 3600 -l ~/Library/Keychains/travis.keychain
  - security import ./.travis_files/yukimura1227_apple.p12 -k ~/Library/Keychains/travis.keychain -P $CERT_PASS -A
  - "security set-key-partition-list -S apple-tool:,apple: -s -k travis travis.keychain"
script:
  - yarn run webpack
  - yarn run test
  - yarn run pack
env:
  global:
    - secure: yc3UWG2PXaXf1r66y9EryPESmSTxhpKzBkxEuMejlKNddFV6AJJsAY6OdSOQt8gteF+uO2cIGlgup+DfyQUZL16ZXvxP0JAAEpkfu6MLJZeISMnZKJXz0O+hmM9RcnC951ppiPIL/mFo4Tb89Ns8zlhO+xwrudBh5GHk/gpobE85yPnB8AvcJWZll2S4l42yz7P7CSu5cIljdg4JAZhhcsWXBwaFjJK6rF3OhZ1zq1TEBq6Jl2wIlO18HiVtjaLdufE7Hx6kJ4HCAZa8gKUxgJWBRyUn/k+VQAg391YUNcNPAQSDnJbHmY19QhYkeAvAHoXLeMqdHBCabqaIfBGj5ryn4mErnpe/ZLFmFxrQDKcMiE8Bzh6kRDZnkzGSFlkwNCN7bYWIhdrxux4995TKB620O/LRVnBaMAXUnDiWMEKO1XY28sLmZghndtsDb3rVBlm0Uz5rU8C9ULsO1UkpcA1lpB7s1aBQ1gzMXMkcj1/X7wz53TV4nKmVTnhYNDCZr2MGa8GtNbRRsHhKaJJbzbmFjakcvDlOH3qmktFFNK9fTsgMONoPAnEzJprhEiPjtGPIdHXuoXse7AidX33Imy0v6i49p+XtJk7n81nVClH4Mv2kDDl/s/MWIK1e1LjfiEZATKZwkKEb9sNg/0EllBvj+GRnWaz0C+NBKSn7Mkg=
    - secure: rDhv9ajXebXjvOGqxE6HDF0axCIPyHk6hVomPfiv2CN80eslxjcRCsAUoZgZArtGYdqmdSC3pVhPuy2+h+rRiPG+IZ/1GjNwSP/oacZrj+LSENjavSnIRCXwJj7ivVPBtNMfSP707zo6tFC6tc4IwJNhOJAuRLnt4TdbEkXE9i/YqJMTbQWSLejXcoJP2by33fy8JIL4wizBi0QceATuP5Y59BG2pkKDQNFdvAy+p7H2q+Zp+ltzucrAObw1sRXBM4+ReLHJAjoNBB8oEvy05QCig2/v8UNLzv7I+fdHIbntk//7fk2B6Pr1IbOGcaucdAAZbL7aXOK2w3K0NHeQPhqKz7RVn8+nefCMsuVWptkCy554vnL21tO8PoErNGgvCew2hcMBSdNMeEdnzZBCih6f3fCZ19ddwOTt30yaY97MYH3HQCRMvWkAkPaqBdnAF/BXpIYu6ssTaUAdC9ZpgS5mJEPb12f2HttWhVpVPsm2OArKNfp4XMFDimifu43cysXdTlJTv8tIPH/QE9fGZOej9Tjo+OfBKbEF4WLVA5MF57Kw++3B2M+MiJn/dv503BPVHpM9Zn0BvAwbjZ01pppjMMP9U+OmoIPHBfrxWOFJeAdPPRrkT7rVRBgGLRztq1rf2hqmA0wqYV+CFovdFNU4D+Vmn/Ij0FHFJ9ASS7I=
branches:
  only:
  - master
notifications:
  slack:
    secure: BMjY+rFnwqZeQm/KnR23krOXS4JNLW9NUtfkXvVSNWYv+YhdmxvfXyjMf7tSlnl5OKqgNqS4k5og9Fq/dznTzEzEURnBVHQcNZgFEWLDn6ScfMrvJ4ynLZwGdhdUJoyRKxzYxYCYEgu/Ek9rG6e68hjQz+HEHwkP1tr5HyhFTLoUEkSSo8c46vX+5fMWAz+sTpScv8lk0ynEnk7ntEs24wlkcspEu3oUiZnhccynah0OsMwgecak99NL1y/cia7bMwWbsvOKKR9Na5gg808Wh4bd5V8ZOHhTK7CvGCT/Fa1/oQnLFUN33yJsoQ56+0O1e9iC2gMOoikhB5cUly2klGb2g6IrEoB7weIyiGjxiAhXT3SKcCGH1IQpsBx3PoybFJ/bm5zBh7kgylN/9OAfGdMOmy5swus4PS6L+ogYgKkxrJU53beLwugubofW5Afv9Dhv2iyWfdQl5tEMf0/YwPBvY4EMYzGR+JQqAYag7Bjl1Hsg/DucRo/MD5DoN5LTSwfycabLQ0S92K4EATE0zgsgc4FAnu6dvKGDpXVYZgIa2FmpVx5NMQ8F5sTrsfAh/eXgGNTAg7M8y0b5u6CrjWCLxeX9J7Gcr7zIbAK++4OBNYmBQu9kJpUZspBNw83eaXIwYVR/xsj9mcSUHj6CRwAzK2XaTzJpDT8Vn8HsXuc=
